---
-   name: Add GPG key
    apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
        validate_certs: no

-   name: Verify fingerprint
    apt_key:
        id: 0EBFCD88
        state: present

-   name: Get DEB architecture
    shell: dpkg --print-architecture
    register: deb_architecture
    changed_when: false

-   name: Set up the repository
    apt_repository:
        repo: deb [arch={{ deb_architecture.stdout }}] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
        state: present
        filename: containerd
        update_cache: yes

-   name: Install Containerd
    apt:
        name: containerd.io
        state: present
        update_cache: yes
    notify: Start containerd on boot

-   name: Check if containerd_configured.txt file exists
    stat:
        path: "/home/{{ username }}/containerd_configured.txt"
    register: containerd_configured_file_check

-   name: Reset containerd config to default
    shell: sudo containerd config default > /etc/containerd/config.toml
    when: not containerd_configured_file_check.stat.exists

-   name: Configure Containerd for k8s
    lineinfile:
        path: /etc/containerd/config.toml
        search_string: 'SystemdCgroup = false'
        line: 'SystemdCgroup = true'
    when: not containerd_configured_file_check.stat.exists
    notify: Restart containerd after configuration

-   name: Create containerd_configured.txt file
    shell: "touch /home/{{ username }}/containerd_configured.txt"
    when: not containerd_configured_file_check.stat.exists
