---
-   name: Check if ingress_nginx_installed.txt file exists
    stat:
        path: "/home/{{ username }}/ingress_nginx_installed.txt"
    register: ingress_nginx_installed_file_check

-   name: Download ingress nginx deploy.yaml
    shell: cd /home/{{ username }} && sudo wget https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v{{ ingress_nginx_version }}/deploy/static/provider/baremetal/deploy.yaml
    when: not ingress_nginx_installed_file_check.stat.exists

-   name: Service type change
    lineinfile:
        path: /home/{{ username }}/deploy.yaml
        search_string: "  type: NodePort"
        line: "  type: LoadBalancer"
    when: not ingress_nginx_installed_file_check.stat.exists

-   name: Deploy ingress nginx
    shell: sudo kubectl apply -f /home/{{ username }}/deploy.yaml
    when: not ingress_nginx_installed_file_check.stat.exists

-   name: Create ingress_nginx_installed.txt file
    shell: "touch /home/{{ username }}/ingress_nginx_installed.txt"
    when: not ingress_nginx_installed_file_check.stat.exists
