---
-   name: Check if cluster_initialized.txt file exists
    stat:
        path: "/home/{{ username }}/cluster_initialized.txt"
    register: cluster_init_file_check

-   name: Cluster init
    shell: sudo kubeadm init
    when: not cluster_init_file_check.stat.exists

-   name: create .kube directory
    file:
        path: "/root/.kube"
        state: directory
        mode: 0755
    when: not cluster_init_file_check.stat.exists

-   name: copy admin.conf
    copy:
        remote_src: yes
        src: /etc/kubernetes/admin.conf
        dest: "/root/.kube/config"
    when: not cluster_init_file_check.stat.exists

-   name: Install cilium Pod network
    shell: |
        helm repo add cilium https://helm.cilium.io/
        helm install cilium cilium/cilium --version {{ cilium_version }} --namespace kube-system
    when: not cluster_init_file_check.stat.exists

-   name: Get join token
    shell: sudo kubeadm token create  --print-join-command
    register: kubernetes_join_command
    when: not cluster_init_file_check.stat.exists

-   name: Copy join command to local file.
    local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
    when: not cluster_init_file_check.stat.exists

-   name: Create cluster_initialized.txt file
    shell: "touch /home/{{ username }}/cluster_initialized.txt"
    when: not cluster_init_file_check.stat.exists
