---
-   name: Install common dependencies
    apt:
        name:
            - apt-transport-https
            - ca-certificates
            - software-properties-common
            - gnupg
            - sudo
            - ntp
        state: present
        update_cache: yes
    notify: Start ntp on boot
