---
-   name: Add non root user to server
    user:
        name: '{{ username }}'
        password: '*'
        shell: /bin/bash
        append: yes
        groups: sudo

-   name: Allow sudo without password
    lineinfile:
        path: /etc/sudoers
        search_string: "%sudo"
        line: "%sudo   ALL=(ALL:ALL) NOPASSWD:ALL"
