---
-   name: Add GPG key
    apt_key:
        url: https://baltocdn.com/helm/signing.asc
        state: present
        validate_certs: no

-   name: Verify fingerprint
    apt_key:
        id: 7C1A168A
        state: present

-   name: Get DEB architecture
    shell: dpkg --print-architecture
    register: deb_architecture
    changed_when: false

-   name: Set up the repository
    apt_repository:
        repo: deb [arch={{ deb_architecture.stdout }}] https://baltocdn.com/helm/stable/debian/ all main
        state: present
        filename: helm
        update_cache: yes

-   name: Install Helm
    apt:
        name: helm
        state: present
        update_cache: yes
