---
-   name: Configure load kernel modules on startup
    copy:
        dest: "/etc/modules-load.d/k8s.conf"
        content: |
            overlay
            br_netfilter

-   name: Load overlay module
    community.general.modprobe:
        name: overlay
        state: present

-   name: Load br_netfilter module
    community.general.modprobe:
        name: br_netfilter
        state: present

-   name: net.bridge.bridge-nf-call-iptables = 1
    sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: "1"
        sysctl_set: true
        sysctl_file: "/etc/sysctl.d/k8s.conf"
        state: present
        reload: true

-   name: net.bridge.bridge-nf-call-ip6tables = 1
    sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: "1"
        sysctl_set: true
        sysctl_file: "/etc/sysctl.d/k8s.conf"
        state: present
        reload: true

-   name: net.ipv4.ip_forward = 1
    sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        sysctl_set: true
        sysctl_file: "/etc/sysctl.d/k8s.conf"
        state: present
        reload: true
